name: SurfProtect
version: 1.0-SNAPSHOT
description: SurfProtect
api-version: "1.19"

loader: dev.slne.protect.bukkit.BukkitLoader

main: dev.slne.protect.bukkit.BukkitMain

dependencies:
    server:
        CommandAPI:
            load: BEFORE
            required: true
            join-classpath: true
        SurfData:
            load: BEFORE
            required: true
            join-classpath: true
        SurfTransaction:
            load: BEFORE
            required: true
            join-classpath: true
        WorldGuard:
            load: BEFORE
            required: true
            join-classpath: true
